# Generated by Django 3.0.5 on 2020-05-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200508_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Last_name',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
